### ISSUE TITLE
Fix crash in aws sdk

### ISSUE THREAD

**Issue by inian** [supabase/storage-api#141] opened 2022-05-26 05:08 UTC
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24300%20Funded-%2300A156.svg" />](https://issuehunt.io/r/supabase/storage-api/issues/141)

We have seen some crashes because of [this issue](https://github.com/aws/aws-sdk-js-v3/issues/2843) in the aws-sdk. 

I have been able to reliably reproduce this issue using [this script](https://github.com/nodejs/node/issues/39671#issuecomment-992693966) in an EC2 server running ubuntu. I am not able to reproduce it locally on my Mac though.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $300.00)

- [<img src='https://avatars.githubusercontent.com/u/54469796?v=4' alt='supabase' width=24 height=24> supabase](https://issuehunt.io/u/supabase) ($300.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/supabase/storage-api/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by burmecia** [comment] 2022-06-19 23:44
This issue was caused by code reentrant in Node.js http parser, this PR (https://github.com/nodejs/node/pull/43369) is in progress to fix this issue.

**Comment by burmecia** [comment] 2022-06-22 23:50
Upstream node.js has fixed this issue in https://github.com/nodejs/node/pull/43369, should we follow it up?

**Comment by bnjmnt4n** [comment] 2022-07-27 07:39
Closed via #167.

**Closed by bnjmnt4n** 2022-07-27 07:39 UTC
Labels: bug, :dollar: Funded on Issuehunt
