### ISSUE TITLE
Allow uploading from URL

### ISSUE THREAD

**Issue by peachp** [supabase/storage-api#13] opened 2021-04-02 17:47 UTC
# Feature request

## Is your feature request related to a problem? Please describe.
We receive thousands of photos in original quality, typically via Dropbox or other service which can transfer files to Dropbox via the backend "internet highway". Currently we can select photos directly from Dropbox when adding them to Airtable, bypassing the slow down/upload connections to/from my team's laptops.

## Describe the solution you'd like
I will use the Dropbox file picker in our app/CMS which generates temporary URLs to selected files, which I can then pass via the JS client to Supabase storage to upload files directly from Dropbox servers to Supabase/S3.

## Describe alternatives you've considered
My team down/uploading the file, or a server proxy syncing all files from Dropbox to file system and then uploading to Supabase Storage, but this add unnecessary complexity and also I'd have to sync all photos, and not just those we need.

**Comment by samandarco** [comment] 2021-12-09 20:56
please

**Comment by fenos** [comment] 2022-09-26 14:30
Duplicate of https://github.com/supabase/storage-api/issues/81

**Closed by fenos** 2022-09-26 14:30 UTC
Labels: enhancement
