### ISSUE TITLE
The from.download() method doc seems to have an error

### ISSUE THREAD

**Issue by rrrepos** [supabase/storage-api#213] opened 2022-10-26 11:28 UTC
The following is from the documentation

```
try {
  const { data, error } = await supabase
    .storage
    .from('avatars')
    .download('folder/avatar1.png')
 ...
}
catch (error) {
 ...
}
```
However this seems to always return the data as null even if the file exists and policies are set right

But the following seems to work

```
try {
  const res = await supabase
    .storage
    .from('avatars')
    .download('folder/avatar1.png')
   
   if(res.error) throw error

   const _blob = res.data // works
  ....
}
```

**Comment by fenos** [comment] 2023-01-23 11:57
I cannot reproduce this issue, closing it for now.

Feel free to provide more information in case you have still an issue with this

**Closed by fenos** 2023-01-23 11:57 UTC
Labels: documentation
